# AUTO-GENERATED by tools/build_submission.py — do not edit by hand.
from datamodel import OrderDepth, TradingState, Order
from typing import List, Dict
import json
import math

# --- base.py ---
from datamodel import OrderDepth, TradingState, Order
from typing import List


class ProductTrader:
    """
    Base class for all per-product strategy implementations.
    Subclass this and implement `get_orders`.
    """

    def __init__(self, symbol: str, position_limit: int):
        self.symbol = symbol
        self.position_limit = position_limit

    def get_orders(self, state: TradingState) -> List[Order]:
        raise NotImplementedError

    # --- state persistence (round-trips through traderData JSON) ---

    def load_state(self, data: dict) -> None:
        """Called by Trader.run() before get_orders. Restore instance state from data."""

    def dump_state(self, data: dict) -> None:
        """Called by Trader.run() after get_orders. Write instance state back into data."""

    # --- helpers ---

    def best_bid(self, order_depth: OrderDepth) -> int | None:
        return max(order_depth.buy_orders) if order_depth.buy_orders else None

    def best_ask(self, order_depth: OrderDepth) -> int | None:
        return min(order_depth.sell_orders) if order_depth.sell_orders else None

    def mid_price(self, order_depth: OrderDepth) -> float | None:
        bid = self.best_bid(order_depth)
        ask = self.best_ask(order_depth)
        if bid is not None and ask is not None:
            return (bid + ask) / 2
        return None

    def current_position(self, state: TradingState) -> int:
        return state.position.get(self.symbol, 0)

# --- ash_mm.py ---
from datamodel import Order, TradingState
from typing import List
import math

SYMBOL = "ASH_COATED_OSMIUM"
POSITION_LIMIT = 80

# ASH is stationary around 10,000.  Wall-mid (deepest bid/ask average) gives a
# zero-lag fair value — no EMA initialisation cost and no lag from a slow alpha.
# The market spread is ~21 ticks 68% of the time, so overbidding / undercutting
# the best standing orders keeps us inside the spread without a fixed offset.

SKEW_DIV = 20       # softer than v3's 15; avoids over-correction at max pos
TAKE_EDGE = 1       # take anything ≥1 tick through FV
MAX_MAKE_VOL = 25   # cap per passive quote so we don't dump the whole limit at once


class AshMarketMaker(ProductTrader):
    """
    Resin-style market-maker for ASH_COATED_OSMIUM.

    Changes vs v3:
    1. Wall-mid FV instead of slow EMA → zero lag, no initialisation cost.
    2. Sweeps ALL mispriced levels (not just best), tracking remaining capacity
       after each fill → eliminates position-limit violations.
    3. Overbid / undercut best standing orders instead of fixed FV +/- 7.
    4. Inventory flattening at wall_mid when position > +/-5 to free capacity.
    5. MAX_MAKE_VOL cap prevents flooding one side with the entire limit.
    """

    def __init__(
        self,
        symbol: str = SYMBOL,
        position_limit: int = POSITION_LIMIT,
        skew_div: int = SKEW_DIV,
        take_edge: int = TAKE_EDGE,
        max_make_vol: int = MAX_MAKE_VOL,
    ):
        super().__init__(symbol, position_limit)
        self.skew_div = skew_div
        self.take_edge = take_edge
        self.max_make_vol = max_make_vol

    # No persistent state needed — FV is recomputed each tick from wall_mid.

    # --- core logic ---

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        od = state.order_depths.get(self.symbol)
        if od is None:
            return orders

        buy_orders  = sorted(od.buy_orders.items(),  key=lambda x: -x[0])  # highest first
        sell_orders = sorted(od.sell_orders.items(), key=lambda x:  x[0])  # lowest first

        if not buy_orders or not sell_orders:
            return orders

        # Fair value: wall-mid (deepest resting level, zero lag)
        wall_bid = buy_orders[-1][0]
        wall_ask = sell_orders[-1][0]
        wall_mid = (wall_bid + wall_ask) / 2

        # Inventory skew: shift FV toward neutral to lean against the position
        pos      = self.current_position(state)
        skew     = pos / self.skew_div
        fv       = wall_mid - skew

        # Remaining capacity — updated after each take to prevent limit violations
        max_buy  = self.position_limit - pos
        max_sell = self.position_limit + pos

        # PHASE 1: Aggressive takes — sweep all mispriced levels
        for ask_price, ask_vol in sell_orders:
            ask_vol = abs(ask_vol)
            if ask_price <= fv - self.take_edge and max_buy > 0:
                vol = min(ask_vol, max_buy)
                orders.append(Order(self.symbol, ask_price, vol))
                max_buy -= vol
                pos += vol
            # Flatten: if we're short, buy at wall_mid to neutralise
            elif ask_price <= wall_mid and pos < -5 and max_buy > 0:
                vol = min(ask_vol, min(-pos, max_buy))
                orders.append(Order(self.symbol, ask_price, vol))
                max_buy -= vol
                pos += vol

        for bid_price, bid_vol in buy_orders:
            bid_vol = abs(bid_vol)
            if bid_price >= fv + self.take_edge and max_sell > 0:
                vol = min(bid_vol, max_sell)
                orders.append(Order(self.symbol, bid_price, -vol))
                max_sell -= vol
                pos -= vol
            # Flatten: if we're long, sell at wall_mid to neutralise
            elif bid_price >= wall_mid and pos > 5 and max_sell > 0:
                vol = min(bid_vol, min(pos, max_sell))
                orders.append(Order(self.symbol, bid_price, -vol))
                max_sell -= vol
                pos -= vol

        # PHASE 2: Passive quotes — overbid/undercut best standing orders
        bid_price = wall_bid + 1
        for bp, bv in buy_orders:
            overbid = bp + 1
            if bv > 1 and overbid < fv:
                bid_price = max(bid_price, overbid)
                break
            elif bp < fv:
                bid_price = max(bid_price, bp)
                break

        ask_price = wall_ask - 1
        for ap, av in sell_orders:
            av = abs(av)
            undercut = ap - 1
            if av > 1 and undercut > fv:
                ask_price = min(ask_price, undercut)
                break
            elif ap > fv:
                ask_price = min(ask_price, ap)
                break

        # Ensure quotes don't cross
        bid_price = int(bid_price)
        ask_price = int(ask_price)
        if bid_price >= ask_price:
            bid_price = int(math.floor(fv)) - 1
            ask_price = int(math.ceil(fv))  + 1

        buy_vol  = min(max_buy,  self.max_make_vol)
        sell_vol = min(max_sell, self.max_make_vol)

        if buy_vol > 0:
            orders.append(Order(self.symbol, bid_price,  buy_vol))
        if sell_vol > 0:
            orders.append(Order(self.symbol, ask_price, -sell_vol))

        return orders

# --- commodity.py ---
from datamodel import Order, TradingState
from typing import List


class CommodityTrader(ProductTrader):
    """
    Conversion arbitrage for commodity products with a conversion mechanism.
    Exploits price gaps between the exchange price and conversion value.
    """

    def __init__(self, symbol: str, position_limit: int, conversion_cost: float, threshold: float = 1.0):
        """
        Args:
            symbol: Tradeable symbol on the exchange.
            position_limit: Max position.
            conversion_cost: Total cost (fees + transport) per unit converted.
            threshold: Min profit above conversion_cost to trigger conversion.
        """
        super().__init__(symbol, position_limit)
        self.conversion_cost = conversion_cost
        self.threshold = threshold

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        obs = state.observations.conversionObservations.get(self.symbol)
        order_depth = state.order_depths.get(self.symbol)
        if obs is None or order_depth is None:
            return orders

        # obs attributes depend on the round — adapt accordingly
        # e.g. obs.bidPrice, obs.askPrice, obs.transportFees, obs.importTariff
        conversion_ask = getattr(obs, "askPrice", None)
        conversion_bid = getattr(obs, "bidPrice", None)

        exch_bid = self.best_bid(order_depth)
        exch_ask = self.best_ask(order_depth)

        pos = self.current_position(state)

        if conversion_ask is not None and exch_bid is not None:
            profit = exch_bid - conversion_ask - self.conversion_cost
            if profit > self.threshold and pos > -self.position_limit:
                orders.append(Order(self.symbol, exch_bid, -1))

        if conversion_bid is not None and exch_ask is not None:
            profit = conversion_bid - exch_ask - self.conversion_cost
            if profit > self.threshold and pos < self.position_limit:
                orders.append(Order(self.symbol, exch_ask, 1))

        return orders

# --- dynamic_product.py ---
from datamodel import Order, TradingState
from typing import List
from collections import deque


class DynamicProductTrader(ProductTrader):
    """
    Market-making strategy for random-walk / non-stationary products.
    Estimates fair value from a rolling mid-price EMA.
    """

    def __init__(self, symbol: str, position_limit: int, ema_alpha: float = 0.2, half_spread: int = 2):
        super().__init__(symbol, position_limit)
        self.ema_alpha = ema_alpha
        self.half_spread = half_spread
        self.ema: float | None = None

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []
        order_depth = state.order_depths.get(self.symbol)
        if order_depth is None:
            return orders

        mid = self.mid_price(order_depth)
        if mid is None:
            return orders

        if self.ema is None:
            self.ema = mid
        else:
            self.ema = self.ema_alpha * mid + (1 - self.ema_alpha) * self.ema

        pos = self.current_position(state)
        bid_price = round(self.ema - self.half_spread)
        ask_price = round(self.ema + self.half_spread)

        buy_capacity = self.position_limit - pos
        sell_capacity = self.position_limit + pos

        if buy_capacity > 0:
            orders.append(Order(self.symbol, bid_price, buy_capacity))
        if sell_capacity > 0:
            orders.append(Order(self.symbol, ask_price, -sell_capacity))

        return orders

# --- etf_arb.py ---
from datamodel import Order, TradingState
from typing import List


class ETFArbTrader:
    """
    Spread / ETF arbitrage between a basket and its constituents.
    Trades the ETF vs. a weighted combination of component symbols.
    """

    def __init__(self, etf_symbol: str, components: dict[str, float], position_limit: int, threshold: float = 2.0):
        """
        Args:
            etf_symbol: Symbol for the ETF / basket product.
            components: {symbol: weight} mapping for constituents.
            position_limit: Max position on each leg.
            threshold: Min spread (in price units) to trigger a trade.
        """
        self.etf_symbol = etf_symbol
        self.components = components
        self.position_limit = position_limit
        self.threshold = threshold

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        etf_depth = state.order_depths.get(self.etf_symbol)
        if etf_depth is None:
            return orders

        # Compute synthetic NAV from component mid prices
        nav = 0.0
        for symbol, weight in self.components.items():
            depth = state.order_depths.get(symbol)
            if depth is None:
                return orders
            bid = max(depth.buy_orders) if depth.buy_orders else None
            ask = min(depth.sell_orders) if depth.sell_orders else None
            if bid is None or ask is None:
                return orders
            nav += weight * (bid + ask) / 2

        etf_bid = max(etf_depth.buy_orders) if etf_depth.buy_orders else None
        etf_ask = min(etf_depth.sell_orders) if etf_depth.sell_orders else None

        if etf_bid is not None and etf_bid - nav > self.threshold:
            # ETF overpriced — sell ETF, buy components
            orders.append(Order(self.etf_symbol, etf_bid, -1))

        if etf_ask is not None and nav - etf_ask > self.threshold:
            # ETF underpriced — buy ETF, sell components
            orders.append(Order(self.etf_symbol, etf_ask, 1))

        return orders

# --- options.py ---
import math
from datamodel import Order, TradingState
from typing import List


def black_scholes_call(S: float, K: float, T: float, r: float, sigma: float) -> float:
    if T <= 0:
        return max(S - K, 0.0)
    d1 = (math.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    return S * _norm_cdf(d1) - K * math.exp(-r * T) * _norm_cdf(d2)


def implied_vol(market_price: float, S: float, K: float, T: float, r: float,
                tol: float = 1e-6, max_iter: int = 100) -> float:
    """Newton-Raphson IV solver."""
    sigma = 0.5
    for _ in range(max_iter):
        price = black_scholes_call(S, K, T, r, sigma)
        vega = S * math.sqrt(T) * _norm_pdf((math.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * math.sqrt(T)))
        if vega < 1e-10:
            break
        sigma -= (price - market_price) / vega
        sigma = max(sigma, 1e-6)
        if abs(price - market_price) < tol:
            break
    return sigma


def _norm_cdf(x: float) -> float:
    return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0


def _norm_pdf(x: float) -> float:
    return math.exp(-0.5 * x ** 2) / math.sqrt(2 * math.pi)


class OptionsTrader(ProductTrader):
    """
    IV scalping strategy for options products.
    Buys options when IV is below fair_iv, sells when above.
    """

    def __init__(self, symbol: str, position_limit: int, underlying_symbol: str,
                 K: float, T: float, r: float, fair_iv: float, iv_edge: float = 0.02):
        super().__init__(symbol, position_limit)
        self.underlying_symbol = underlying_symbol
        self.K = K
        self.T = T
        self.r = r
        self.fair_iv = fair_iv
        self.iv_edge = iv_edge

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        opt_depth = state.order_depths.get(self.symbol)
        und_depth = state.order_depths.get(self.underlying_symbol)
        if opt_depth is None or und_depth is None:
            return orders

        S_mid = self.mid_price(und_depth)
        if S_mid is None:
            return orders

        opt_ask = min(opt_depth.sell_orders) if opt_depth.sell_orders else None
        opt_bid = max(opt_depth.buy_orders) if opt_depth.buy_orders else None

        pos = self.current_position(state)

        if opt_ask is not None:
            iv = implied_vol(opt_ask, S_mid, self.K, self.T, self.r)
            if iv < self.fair_iv - self.iv_edge and pos < self.position_limit:
                orders.append(Order(self.symbol, opt_ask, 1))

        if opt_bid is not None:
            iv = implied_vol(opt_bid, S_mid, self.K, self.T, self.r)
            if iv > self.fair_iv + self.iv_edge and pos > -self.position_limit:
                orders.append(Order(self.symbol, opt_bid, -1))

        return orders

# --- pepper_mr.py ---
from datamodel import Order, TradingState
from typing import List

SYMBOL = "INTARIAN_PEPPER_ROOT"
POSITION_LIMIT = 50


class PepperMeanReversionTrader(ProductTrader):
    """
    Mean-reversion strategy for INTARIAN_PEPPER_ROOT.

    Logic:
    - Maintains a rolling EMA of the wall mid-price.
    - Goes max-long  when mid < EMA - threshold  (price below fair value).
    - Goes max-short when mid > EMA + threshold  (price above fair value).
    - Flattens toward zero when mid is within the band (no edge).

    State (ema) is persisted across ticks via traderData JSON so that
    the EMA survives re-instantiation on every tick.
    """

    def __init__(
        self,
        symbol: str = SYMBOL,
        position_limit: int = POSITION_LIMIT,
        ema_alpha: float = 0.15,
        threshold: float = 3.0,
    ):
        super().__init__(symbol, position_limit)
        self.ema_alpha = ema_alpha
        self.threshold = threshold
        self.ema: float | None = None

    # ------------------------------------------------------------------
    # State persistence
    # ------------------------------------------------------------------

    def load_state(self, data: dict) -> None:
        self.ema = data.get(self.symbol + "_ema")

    def dump_state(self, data: dict) -> None:
        data[self.symbol + "_ema"] = self.ema

    # ------------------------------------------------------------------
    # Core logic
    # ------------------------------------------------------------------

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        order_depth = state.order_depths.get(self.symbol)
        if order_depth is None:
            return orders

        mid = self.mid_price(order_depth)
        if mid is None:
            return orders

        # Update EMA — warm-start on first tick
        if self.ema is None:
            self.ema = mid
        else:
            self.ema = self.ema_alpha * mid + (1 - self.ema_alpha) * self.ema

        pos = self.current_position(state)
        best_ask = self.best_ask(order_depth)
        best_bid = self.best_bid(order_depth)

        deviation = mid - self.ema

        if deviation < -self.threshold:
            # Price is cheap relative to EMA — go long
            if best_ask is not None:
                buy_qty = self.position_limit - pos   # fill up to limit
                if buy_qty > 0:
                    orders.append(Order(self.symbol, best_ask, buy_qty))

        elif deviation > self.threshold:
            # Price is rich relative to EMA — go short
            if best_bid is not None:
                sell_qty = self.position_limit + pos  # sell down to -limit
                if sell_qty > 0:
                    orders.append(Order(self.symbol, best_bid, -sell_qty))

        else:
            # Inside the band — exit any open position
            if pos > 0 and best_bid is not None:
                orders.append(Order(self.symbol, best_bid, -pos))
            elif pos < 0 and best_ask is not None:
                orders.append(Order(self.symbol, best_ask, -pos))

        return orders

# --- pepper_trend.py ---
from datamodel import Order, TradingState
from typing import List

SYMBOL = "INTARIAN_PEPPER_ROOT"
POSITION_LIMIT = 80

# Pepper trended +3,000 over 3 days — non-stationary, purely directional.
# Strategy: build max long as efficiently as possible, then hold.
#
# Hybrid entry splits the load:
#   - First AGGRESSIVE_TARGET units: take best ask immediately (need exposure fast)
#   - Remaining units: limit bids at bb+1 -> saves ~10 ticks per passive fill
#     vs slamming the ask, recovering 300-400 PnL and reducing initial drawdown.
#
# Once full: only post an impossibly wide ask (ba+20) — almost never fills,
# preserving the long position to ride the full trend.

AGGRESSIVE_TARGET = 80   # take aggressively up to this many units
MAX_PASSIVE_VOL   = 20   # max volume per passive bid layer


class PepperTrendTrader(ProductTrader):
    """
    Hybrid directional loader for INTARIAN_PEPPER_ROOT.

    Changes vs v3:
    1. Two-phase entry: aggressive take for first 40 units, then limit bids
       at bb+1 for remaining 40 -> saves ~10 ticks/unit on passive fills.
    2. Second passive layer at best_bid mops up remaining capacity.
    3. Wide ask (ba+20) once full — avoids accidentally resetting position
       and restarting the entry cost.
    """

    def __init__(
        self,
        symbol: str = SYMBOL,
        position_limit: int = POSITION_LIMIT,
        aggressive_target: int = AGGRESSIVE_TARGET,
        max_passive_vol: int = MAX_PASSIVE_VOL,
    ):
        super().__init__(symbol, position_limit)
        self.aggressive_target = aggressive_target
        self.max_passive_vol = max_passive_vol

    # No persistent state needed — logic is purely positional.

    # --- core logic ---

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        od = state.order_depths.get(self.symbol)
        if od is None:
            return orders

        buy_orders  = sorted(od.buy_orders.items(),  key=lambda x: -x[0])
        sell_orders = sorted(od.sell_orders.items(), key=lambda x:  x[0])

        pos       = self.current_position(state)
        remaining = self.position_limit - pos

        # Already at max long — post a wide ask to avoid accidental unwind
        if remaining <= 0:
            if sell_orders:
                widest_ask = sell_orders[-1][0]
                orders.append(Order(self.symbol, widest_ask + 20, -1))
            return orders

        if not sell_orders and not buy_orders:
            return orders

        best_ask     = sell_orders[0][0] if sell_orders else None
        best_ask_vol = abs(sell_orders[0][1]) if sell_orders else 0
        best_bid     = buy_orders[0][0] if buy_orders else None

        # PHASE 1: Aggressive — take best ask until AGGRESSIVE_TARGET units held
        if pos < self.aggressive_target and best_ask is not None:
            aggressive_remaining = self.aggressive_target - pos
            take_vol = min(best_ask_vol, aggressive_remaining, remaining)
            if take_vol > 0:
                orders.append(Order(self.symbol, best_ask, take_vol))
                remaining -= take_vol
                pos += take_vol

        # PHASE 2: Passive layer at bb+1 (saves ~10 ticks vs slamming the ask)
        if remaining > 0 and best_bid is not None:
            passive_vol = min(remaining, self.max_passive_vol)
            orders.append(Order(self.symbol, best_bid + 1, passive_vol))
            remaining -= passive_vol

        # PHASE 3: Second layer at best_bid — mop up leftover capacity
        if remaining > 0 and best_bid is not None:
            orders.append(Order(self.symbol, best_bid, remaining))

        return orders

# --- static_product.py ---
from datamodel import Order, TradingState
from typing import List


class StaticProductTrader(ProductTrader):
    """
    Market-making strategy for stationary / mean-reverting products.
    Quotes around a fair value with a configurable spread.
    """

    def __init__(self, symbol: str, position_limit: int, fair_value: float, half_spread: int = 1):
        super().__init__(symbol, position_limit)
        self.fair_value = fair_value
        self.half_spread = half_spread

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []
        pos = self.current_position(state)

        bid_price = round(self.fair_value - self.half_spread)
        ask_price = round(self.fair_value + self.half_spread)

        buy_capacity = self.position_limit - pos
        sell_capacity = self.position_limit + pos

        if buy_capacity > 0:
            orders.append(Order(self.symbol, bid_price, buy_capacity))
        if sell_capacity > 0:
            orders.append(Order(self.symbol, ask_price, -sell_capacity))

        return orders

# --- trader_v1.py ---
from datamodel import OrderDepth, UserId, TradingState, Order
from typing import List, Dict
import json
import math

class Trader:
    def __init__(self):
        # Set your position limits here. (Update these if Round 1 rules specify different limits)
        self.POSITION_LIMITS = {
            "ASH_COATED_OSMIUM": 20,
            "INTARIAN_PEPPER_ROOT": 20
        }
        
        # Configuration for ASH_COATED_OSMIUM (Stationary)
        self.ASH_FAIR_VALUE = 10000
        
        # Configuration for INTARIAN_PEPPER_ROOT (Trending)
        self.PEPPER_EMA_ALPHA = 0.2  # Smoothing factor (higher = reacts to price changes faster)

    def run(self, state: TradingState):
        """
        Only method required. It takes all inputs and returns a tuple of (orders, conversions, trader_data).
        """
        # Dictionary to hold the orders for each product
        result = {}
        
        # We start by parsing the persistent state from the previous timestamp (used for the EMA)
        trader_data = {}
        if state.traderData:
            try:
                trader_data = json.loads(state.traderData)
            except Exception as e:
                pass # If it's the first timestamp or corrupted, start fresh
                
        # ---------------------------------------------------------
        # 1. Process ASH_COATED_OSMIUM (The "Anchor" Strategy)
        # ---------------------------------------------------------
        ash_product = "ASH_COATED_OSMIUM"
        if ash_product in state.order_depths:
            order_depth: OrderDepth = state.order_depths[ash_product]
            orders: List[Order] = []
            
            # Get current position and calculate limits
            current_position = state.position.get(ash_product, 0)
            limit = self.POSITION_LIMITS[ash_product]
            
            # --- MARKET TAKING (Clear "Free Money") ---
            # Buy if someone is selling below fair value
            if len(order_depth.sell_orders) != 0:
                best_ask, best_ask_amount = list(order_depth.sell_orders.items())[0]
                if best_ask < self.ASH_FAIR_VALUE:
                    buy_amount = min(-best_ask_amount, limit - current_position)
                    if buy_amount > 0:
                        orders.append(Order(ash_product, best_ask, buy_amount))
                        current_position += buy_amount

            # Sell if someone is buying above fair value
            if len(order_depth.buy_orders) != 0:
                best_bid, best_bid_amount = list(order_depth.buy_orders.items())[0]
                if best_bid > self.ASH_FAIR_VALUE:
                    sell_amount = max(-best_bid_amount, -limit - current_position) # sell amounts are negative
                    if sell_amount < 0:
                        orders.append(Order(ash_product, best_bid, sell_amount))
                        current_position += sell_amount

            # --- MARKET MAKING (Capture the spread) ---
            # How much room do we have left to trade?
            max_buy = limit - current_position
            max_sell = -limit - current_position

            # Shift quotes based on inventory to prevent hitting the limit
            position_skew = int(current_position / 4)
            
            my_bid = self.ASH_FAIR_VALUE - 4 - position_skew
            my_ask = self.ASH_FAIR_VALUE + 4 - position_skew

            # Place the passive orders if we have room
            if max_buy > 0:
                orders.append(Order(ash_product, my_bid, max_buy))
            if max_sell < 0:
                orders.append(Order(ash_product, my_ask, max_sell))

            result[ash_product] = orders


        # ---------------------------------------------------------
        # 2. Process INTARIAN_PEPPER_ROOT (The "Escalator" + OBI Protection)
        # ---------------------------------------------------------
        pepper_product = "INTARIAN_PEPPER_ROOT"
        if pepper_product in state.order_depths:
            order_depth: OrderDepth = state.order_depths[pepper_product]
            orders: List[Order] = []
            
            current_position = state.position.get(pepper_product, 0)
            limit = self.POSITION_LIMITS[pepper_product]
            
            if len(order_depth.sell_orders) > 0 and len(order_depth.buy_orders) > 0:
                best_ask, best_ask_amount = list(order_depth.sell_orders.items())[0]
                best_bid, best_bid_amount = list(order_depth.buy_orders.items())[0]
                mid_price = (best_ask + best_bid) / 2.0
                
                # --- ORDER BOOK IMBALANCE (OBI) CALCULATION ---
                # Note: ask amounts are negative in the datamodel, so we use abs()
                total_volume = best_bid_amount + abs(best_ask_amount)
                obi = best_bid_amount / total_volume if total_volume > 0 else 0.5
            else:
                mid_price = None

            if mid_price is not None:
                # Update Exponential Moving Average (EMA)
                prev_ema = trader_data.get("pepper_ema", mid_price)
                current_ema = (self.PEPPER_EMA_ALPHA * mid_price) + ((1 - self.PEPPER_EMA_ALPHA) * prev_ema)
                trader_data["pepper_ema"] = current_ema
                
                my_bid = math.floor(current_ema - 3)
                my_ask = math.ceil(current_ema + 6) 
                
                max_buy = limit - current_position
                max_sell = -limit - current_position
                
                # --- OBI PROTECTION LOGIC ---
                if obi > 0.8:
                    # Massive buying pressure: Price is about to spike!
                    # Cancel our market-making asks so we don't get run over.
                    max_sell = 0 
                elif obi < 0.2:
                    # Massive selling pressure: Price is about to dump!
                    # Cancel our market-making bids so we don't catch a falling knife.
                    max_buy = 0
                
                # Opportunistic Market Taking: Aggressive buy if price dips significantly below the EMA
                # (We still allow this even if OBI is low, because a massive dip below EMA is highly profitable)
                if best_ask < current_ema - 2:
                    buy_amount = min(abs(best_ask_amount), max_buy)
                    if buy_amount > 0:
                        orders.append(Order(pepper_product, best_ask, buy_amount))
                        max_buy -= buy_amount
                        current_position += buy_amount
                        max_sell = -limit - current_position # Re-adjust sell limit after taking
                
                # Place Market Making Orders around the moving average (filtered by OBI)
                if max_buy > 0:
                    orders.append(Order(pepper_product, my_bid, max_buy))
                if max_sell < 0: # Note: max_sell is negative, so this checks if we still want to sell
                    orders.append(Order(pepper_product, my_ask, max_sell))
                    
            result[pepper_product] = orders

        # ---------------------------------------------------------
        # 3. Finalize and Return
        # ---------------------------------------------------------
        
        # Serialize the trader data state so it can be passed into the next timestamp
        next_trader_data = json.dumps(trader_data)
        conversions = 0 # No conversions in Round 1 usually
        
        return result, conversions, next_trader_data

STRATEGIES: List[ProductTrader] = [
    AshMarketMaker(symbol="ASH_COATED_OSMIUM",       position_limit=80),
    PepperTrendTrader(symbol="INTARIAN_PEPPER_ROOT", position_limit=80),
]


class Trader:

    def run(self, state: TradingState):
        trader_data: dict = json.loads(state.traderData) if state.traderData else {}

        for s in STRATEGIES:
            s.load_state(trader_data)

        result: Dict[str, List[Order]] = {}
        for s in STRATEGIES:
            result[s.symbol] = s.get_orders(state)

        for s in STRATEGIES:
            s.dump_state(trader_data)

        return result, 0, json.dumps(trader_data)
