#!/usr/bin/env python3
"""
build_submission.py — Merges strategy modules into a single submission.py.

Usage:
    python tools/build_submission.py
"""

import ast
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
STRATEGIES_DIR = ROOT / "strategies"
OUTPUT = ROOT / "submission.py"
DATAMODEL = ROOT / "datamodel.py"

HEADER = '''# AUTO-GENERATED by tools/build_submission.py — do not edit by hand.
from datamodel import OrderDepth, TradingState, Order
from typing import List, Dict
import json
import math

'''

TRADER_CLASS = '''

STRATEGIES: List[ProductTrader] = [
    AshMarketMaker(symbol="ASH_COATED_OSMIUM",       position_limit=80),
    PepperTrendTrader(symbol="INTARIAN_PEPPER_ROOT", position_limit=80),
]


class Trader:

    def run(self, state: TradingState):
        trader_data: dict = json.loads(state.traderData) if state.traderData else {}

        for s in STRATEGIES:
            s.load_state(trader_data)

        result: Dict[str, List[Order]] = {}
        for s in STRATEGIES:
            result[s.symbol] = s.get_orders(state)

        for s in STRATEGIES:
            s.dump_state(trader_data)

        return result, 0, json.dumps(trader_data)
'''


def collect_strategy_source() -> str:
    parts = []
    paths = [p for p in STRATEGIES_DIR.glob("*.py") if p.name != "__init__.py"]

    # Ensure base class definitions are emitted before strategy modules
    # that inherit from them.
    paths.sort(key=lambda p: (0 if p.name == "base.py" else 1, p.name))

    for path in paths:
        src = path.read_text(encoding="utf-8")
        # Strip relative imports — they won't work in the merged file
        lines = [l for l in src.splitlines() if not l.startswith("from strategies")]
        parts.append(f"# --- {path.name} ---\n" + "\n".join(lines))
    return "\n\n".join(parts)


def build():
    strategy_src = collect_strategy_source()
    output = HEADER + strategy_src + TRADER_CLASS
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Submission written to {OUTPUT}  ({len(output)} chars)")


if __name__ == "__main__":
    build()
